/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hotel } from '../../models/hotel';

export interface HotelControllerGetAllHotels$Params {
}

export function hotelControllerGetAllHotels(http: HttpClient, rootUrl: string, params?: HotelControllerGetAllHotels$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Hotel>>> {
  const rb = new RequestBuilder(rootUrl, hotelControllerGetAllHotels.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Hotel>>;
    })
  );
}

hotelControllerGetAllHotels.PATH = '/hotels';
