/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { Client } from './models/client';
export { CreateClientRequestDto } from './models/create-client-request-dto';
export { CreateHotelBookingRequestDto } from './models/create-hotel-booking-request-dto';
export { CreateHotelRequestDto } from './models/create-hotel-request-dto';
export { Hotel } from './models/hotel';
export { HotelBooking } from './models/hotel-booking';
export { UpdateHotelBookingRequestDto } from './models/update-hotel-booking-request-dto';
export { UpdateHotelRequestDto } from './models/update-hotel-request-dto';
