/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Client } from './models/client';
export type { CreateClientRequestDto } from './models/create-client-request-dto';
export type { CreateHotelBookingRequestDto } from './models/create-hotel-booking-request-dto';
export type { CreateHotelRequestDto } from './models/create-hotel-request-dto';
export type { UpdateHotelBookingRequestDto } from './models/update-hotel-booking-request-dto';
export type { UpdateHotelRequestDto } from './models/update-hotel-request-dto';
