/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ClientsService } from './services/clients.service';
export { HotelsService } from './services/hotels.service';
export { HotelBookingsService } from './services/hotel-bookings.service';
