/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Client } from '../models/client';
import { Hotel } from '../models/hotel';
export interface HotelBooking {
  address: string;
  client: Client;
  createdDate: string;
  hotel: Hotel;
  id: string;
  name: string;
}
