/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelBooking } from '../models/hotel-booking';
export interface Hotel {
  address: string;
  createdDate: string;
  hotelBookings: Array<HotelBooking>;
  id: string;
  name: string;
}
